package charts

import "github.com/a-h/templ"

// Component resolves a gallery chart by its registry name for the /view
// iframe route, the pendant of shadcn's getRegistryComponent.
func Component(name string) templ.Component {
	switch name {
	case "chart-area-interactive":
		return ChartAreaInteractive()
	case "chart-area-default":
		return ChartAreaDefault()
	case "chart-area-linear":
		return ChartAreaLinear()
	case "chart-area-step":
		return ChartAreaStep()
	case "chart-area-legend":
		return ChartAreaLegend()
	case "chart-area-stacked":
		return ChartAreaStacked()
	case "chart-area-gradient":
		return ChartAreaGradient()
	case "chart-area-axes":
		return ChartAreaAxes()
	case "chart-area-icons":
		return ChartAreaIcons()
	case "chart-area-stacked-expand":
		return ChartAreaStackedExpand()
	case "chart-bar-interactive":
		return ChartBarInteractive()
	case "chart-bar-default":
		return ChartBarDefault()
	case "chart-bar-horizontal":
		return ChartBarHorizontal()
	case "chart-bar-multiple":
		return ChartBarMultiple()
	case "chart-bar-stacked":
		return ChartBarStacked()
	case "chart-bar-label":
		return ChartBarLabel()
	case "chart-bar-label-custom":
		return ChartBarLabelCustom()
	case "chart-bar-mixed":
		return ChartBarMixed()
	case "chart-bar-active":
		return ChartBarActive()
	case "chart-bar-negative":
		return ChartBarNegative()
	case "chart-line-interactive":
		return ChartLineInteractive()
	case "chart-line-default":
		return ChartLineDefault()
	case "chart-line-linear":
		return ChartLineLinear()
	case "chart-line-step":
		return ChartLineStep()
	case "chart-line-multiple":
		return ChartLineMultiple()
	case "chart-line-dots":
		return ChartLineDots()
	case "chart-line-dots-custom":
		return ChartLineDotsCustom()
	case "chart-line-dots-colors":
		return ChartLineDotsColors()
	case "chart-line-label":
		return ChartLineLabel()
	case "chart-line-label-custom":
		return ChartLineLabelCustom()
	case "chart-radar-default":
		return ChartRadarDefault()
	case "chart-radar-dots":
		return ChartRadarDots()
	case "chart-radar-lines-only":
		return ChartRadarLinesOnly()
	case "chart-radar-label-custom":
		return ChartRadarLabelCustom()
	case "chart-radar-grid-custom":
		return ChartRadarGridCustom()
	case "chart-radar-grid-none":
		return ChartRadarGridNone()
	case "chart-radar-grid-circle":
		return ChartRadarGridCircle()
	case "chart-radar-grid-circle-no-lines":
		return ChartRadarGridCircleNoLines()
	case "chart-radar-grid-circle-fill":
		return ChartRadarGridCircleFill()
	case "chart-radar-grid-fill":
		return ChartRadarGridFill()
	case "chart-radar-multiple":
		return ChartRadarMultiple()
	case "chart-radar-legend":
		return ChartRadarLegend()
	case "chart-pie-simple":
		return ChartPieSimple()
	case "chart-pie-separator-none":
		return ChartPieSeparatorNone()
	case "chart-pie-label":
		return ChartPieLabel()
	case "chart-pie-label-custom":
		return ChartPieLabelCustom()
	case "chart-pie-label-list":
		return ChartPieLabelList()
	case "chart-pie-legend":
		return ChartPieLegend()
	case "chart-pie-donut-active":
		return ChartPieDonutActive()
	case "chart-pie-donut-text":
		return ChartPieDonutText()
	case "chart-pie-stacked":
		return ChartPieStacked()
	case "chart-pie-donut":
		return ChartPieDonut()
	case "chart-pie-interactive":
		return ChartPieInteractive()
	}
	return nil
}
