package examples

import "github.com/a-h/templ"

// RegistryEntry links a demo name (the shadcn mdx name, e.g. "button-demo")
// to our example component and its source file for the code block.
type RegistryEntry struct {
	Component templ.Component
	File      string
}

// Registry resolves <ComponentPreview name="..."/> shortcodes in the
// markdown component docs. Grows page by page during the docs migration.
var Registry = map[string]RegistryEntry{
	"date-picker-demo": {Component: DatePickerDemo(), File: "date_picker_demo.templ"},
	"date-picker-basic": {Component: DatePickerBasic(), File: "date_picker_basic.templ"},
	"date-picker-range": {Component: DatePickerRange(), File: "date_picker_range.templ"},
	"date-picker-dob": {Component: DatePickerDob(), File: "date_picker_dob.templ"},
	"date-picker-input": {Component: DatePickerInput(), File: "date_picker_input.templ"},
	"date-picker-time": {Component: DatePickerTime(), File: "date_picker_time.templ"},
	"context-menu-demo": {Component: ContextMenuDemo(), File: "contextmenu_demo.templ"},
	"context-menu-basic": {Component: ContextMenuBasic(), File: "contextmenu_basic.templ"},
	"context-menu-submenu": {Component: ContextMenuSubmenu(), File: "contextmenu_submenu.templ"},
	"context-menu-shortcuts": {Component: ContextMenuShortcuts(), File: "contextmenu_shortcuts.templ"},
	"context-menu-groups": {Component: ContextMenuGroups(), File: "contextmenu_groups.templ"},
	"context-menu-icons": {Component: ContextMenuIcons(), File: "contextmenu_icons.templ"},
	"context-menu-checkboxes": {Component: ContextMenuCheckboxes(), File: "contextmenu_checkboxes.templ"},
	"context-menu-radio": {Component: ContextMenuRadio(), File: "contextmenu_radio.templ"},
	"context-menu-destructive": {Component: ContextMenuDestructive(), File: "contextmenu_destructive.templ"},
	"context-menu-sides": {Component: ContextMenuSides(), File: "contextmenu_sides.templ"},
	"combobox-demo": {Component: ComboboxDemo(), File: "combobox_demo.templ"},
	"combobox-basic": {Component: ComboboxBasic(), File: "combobox_basic.templ"},
	"combobox-multiple": {Component: ComboboxMultiple(), File: "combobox_multiple.templ"},
	"combobox-clear": {Component: ComboboxClear(), File: "combobox_clear.templ"},
	"combobox-groups": {Component: ComboboxGroups(), File: "combobox_groups.templ"},
	"combobox-custom": {Component: ComboboxCustom(), File: "combobox_custom.templ"},
	"combobox-invalid": {Component: ComboboxInvalid(), File: "combobox_invalid.templ"},
	"combobox-disabled": {Component: ComboboxDisabled(), File: "combobox_disabled.templ"},
	"combobox-auto-highlight": {Component: ComboboxAutoHighlight(), File: "combobox_auto_highlight.templ"},
	"combobox-popup": {Component: ComboboxPopup(), File: "combobox_popup.templ"},
	"combobox-input-group": {Component: ComboboxInputGroup(), File: "combobox_input_group.templ"},
	"carousel-demo": {Component: CarouselDemo(), File: "carousel_demo.templ"},
	"carousel-size": {Component: CarouselSize(), File: "carousel_size.templ"},
	"carousel-spacing": {Component: CarouselSpacing(), File: "carousel_spacing.templ"},
	"carousel-orientation": {Component: CarouselOrientation(), File: "carousel_orientation.templ"},
	"carousel-api": {Component: CarouselApi(), File: "carousel_api.templ"},
	"carousel-plugin": {Component: CarouselPlugin(), File: "carousel_plugin.templ"},
	"calendar-demo": {Component: CalendarDemo(), File: "calendar_demo.templ"},
	"calendar-basic": {Component: CalendarBasic(), File: "calendar_basic.templ"},
	"calendar-range": {Component: CalendarRange(), File: "calendar_range.templ"},
	"calendar-caption": {Component: CalendarCaption(), File: "calendar_caption.templ"},
	"calendar-presets": {Component: CalendarPresets(), File: "calendar_presets.templ"},
	"calendar-time": {Component: CalendarTime(), File: "calendar_time.templ"},
	"calendar-booked-dates": {Component: CalendarBookedDates(), File: "calendar_booked_dates.templ"},
	"calendar-custom-days": {Component: CalendarCustomCellSize(), File: "calendar_custom_days.templ"},
	"calendar-week-numbers": {Component: CalendarWeekNumbers(), File: "calendar_week_numbers.templ"},
	"button-group-orientation": {Component: ButtonGroupOrientation(), File: "buttongroup_orientation.templ"},
	"button-group-size": {Component: ButtonGroupSize(), File: "buttongroup_size.templ"},
	"button-group-nested": {Component: ButtonGroupNested(), File: "buttongroup_nested.templ"},
	"button-group-separator": {Component: ButtonGroupSeparatorExample(), File: "buttongroup_separator.templ"},
	"button-group-split": {Component: ButtonGroupSplit(), File: "buttongroup_split.templ"},
	"button-group-input": {Component: ButtonGroupInput(), File: "buttongroup_input.templ"},
	"button-group-input-group": {Component: ButtonGroupInputGroup(), File: "buttongroup_input_group.templ"},
	"button-group-dropdown": {Component: ButtonGroupDropdown(), File: "buttongroup_dropdown.templ"},
	"button-group-select": {Component: ButtonGroupSelect(), File: "buttongroup_select.templ"},
	"button-group-popover": {Component: ButtonGroupPopover(), File: "buttongroup_popover.templ"},
	"card-demo": {Component: CardDemo(), File: "card_demo.templ"},
	"card-small": {Component: CardSmall(), File: "card_small.templ"},
	"card-spacing": {Component: CardSpacing(), File: "card_spacing.templ"},
	"card-edge-to-edge": {Component: CardEdgeToEdge(), File: "card_edge_to_edge.templ"},
	"card-image": {Component: CardImage(), File: "card_image.templ"},
	"checkbox-demo": {Component: CheckboxDemo(), File: "checkbox_demo.templ"},
	"checkbox-basic": {Component: CheckboxBasic(), File: "checkbox_basic.templ"},
	"checkbox-invalid": {Component: CheckboxInvalid(), File: "checkbox_invalid.templ"},
	"checkbox-description": {Component: CheckboxDescription(), File: "checkbox_description.templ"},
	"checkbox-disabled": {Component: CheckboxDisabled(), File: "checkbox_disabled.templ"},
	"checkbox-group": {Component: CheckboxGroup(), File: "checkbox_group.templ"},
	"checkbox-table": {Component: CheckboxTable(), File: "checkbox_table.templ"},
	"collapsible-demo": {Component: CollapsibleDemo(), File: "collapsible_demo.templ"},
	"collapsible-basic": {Component: CollapsibleBasic(), File: "collapsible_basic.templ"},
	"collapsible-settings": {Component: CollapsibleSettings(), File: "collapsible_settings.templ"},
	"collapsible-file-tree": {Component: CollapsibleFileTree(), File: "collapsible_file_tree.templ"},
	"accordion-demo": {Component: AccordionDemo(), File: "accordion_demo.templ"},
	"accordion-basic": {Component: AccordionBasic(), File: "accordion_basic.templ"},
	"accordion-multiple": {Component: AccordionMultiple(), File: "accordion_multiple.templ"},
	"accordion-disabled": {Component: AccordionDisabled(), File: "accordion_disabled.templ"},
	"accordion-borders": {Component: AccordionBorders(), File: "accordion_borders.templ"},
	"accordion-card": {Component: AccordionCard(), File: "accordion_card.templ"},
	"alert-demo": {Component: AlertDemo(), File: "alert_demo.templ"},
	"alert-basic": {Component: AlertBasic(), File: "alert_basic.templ"},
	"alert-destructive": {Component: AlertDestructive(), File: "alert_destructive.templ"},
	"alert-action": {Component: AlertAction(), File: "alert_action.templ"},
	"alert-colors": {Component: AlertColors(), File: "alert_colors.templ"},
	"aspect-ratio-demo": {Component: AspectRatioDemo(), File: "aspect_ratio_demo.templ"},
	"aspect-ratio-square": {Component: AspectRatioSquare(), File: "aspect_ratio_square.templ"},
	"aspect-ratio-portrait": {Component: AspectRatioPortrait(), File: "aspect_ratio_portrait.templ"},
	"avatar-demo": {Component: AvatarDemo(), File: "avatar_demo.templ"},
	"avatar-basic": {Component: AvatarBasic(), File: "avatar_basic.templ"},
	"avatar-badge": {Component: AvatarBadgeExample(), File: "avatar_badge.templ"},
	"avatar-badge-icon": {Component: AvatarBadgeIcon(), File: "avatar_badge_icon.templ"},
	"avatar-group": {Component: AvatarGroup(), File: "avatar_group.templ"},
	"avatar-group-count": {Component: AvatarGroupCount(), File: "avatar_group_count.templ"},
	"avatar-group-count-icon": {Component: AvatarGroupCountIcon(), File: "avatar_group_count_icon.templ"},
	"avatar-size": {Component: AvatarSize(), File: "avatar_size.templ"},
	"avatar-dropdown": {Component: AvatarDropdown(), File: "avatar_dropdown.templ"},
	"badge-demo": {Component: BadgeDemo(), File: "badge_demo.templ"},
	"badge-variants": {Component: BadgeVariants(), File: "badge_variants.templ"},
	"badge-icon": {Component: BadgeIcon(), File: "badge_icon.templ"},
	"badge-spinner": {Component: BadgeSpinner(), File: "badge_spinner.templ"},
	"badge-link": {Component: BadgeLink(), File: "badge_link.templ"},
	"badge-colors": {Component: BadgeColors(), File: "badge_colors.templ"},
	"breadcrumb-demo": {Component: BreadcrumbDemo(), File: "breadcrumb_demo.templ"},
	"breadcrumb-basic": {Component: BreadcrumbBasic(), File: "breadcrumb_basic.templ"},
	"breadcrumb-separator": {Component: BreadcrumbSeparator(), File: "breadcrumb_separator.templ"},
	"breadcrumb-dropdown": {Component: BreadcrumbDropdown(), File: "breadcrumb_dropdown.templ"},
	"breadcrumb-ellipsis": {Component: BreadcrumbEllipsisDemo(), File: "breadcrumb_ellipsis.templ"},
	"breadcrumb-link": {Component: BreadcrumbLink(), File: "breadcrumb_link.templ"},
	"button-demo":        {Component: ButtonDemo(), File: "button_demo.templ"},
	"button-size":        {Component: ButtonSize(), File: "button_size.templ"},
	"button-default":     {Component: ButtonDefault(), File: "button_default.templ"},
	"button-outline":     {Component: ButtonOutline(), File: "button_outline.templ"},
	"button-secondary":   {Component: ButtonSecondary(), File: "button_secondary.templ"},
	"button-ghost":       {Component: ButtonGhost(), File: "button_ghost.templ"},
	"button-destructive": {Component: ButtonDestructive(), File: "button_destructive.templ"},
	"button-link":        {Component: ButtonLink(), File: "button_link.templ"},
	"button-icon":        {Component: ButtonIcon(), File: "button_icon.templ"},
	"button-with-icon":   {Component: ButtonWithIcon(), File: "button_with_icon.templ"},
	"button-rounded":     {Component: ButtonRounded(), File: "button_rounded.templ"},
	"button-spinner":     {Component: ButtonSpinner(), File: "button_spinner.templ"},
	"button-group-demo":  {Component: ButtonGroupDemo(), File: "buttongroup_demo.templ"},
	"button-render":      {Component: ButtonRender(), File: "button_render.templ"},
}
